# Generated by Django 3.0 on 2019-12-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_email',
            name='token',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
